server:
  port: 7040

spring:
  application:
    name: SONG-MS
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_case_study
    username: root
    password: Sunrise.123
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
ARTIST-MS:
  ribbon:
    eureka:
      enabled:false
    listOfServers: localhost:7050,localhost:7060, localhost:7070
    ServerListRefreshInterval: 15000  